runtime: python27
api_version: 1
threadsafe: true
instance_class: F4_HIGHMEM

libraries:
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

